version: '3.8'

services:
   postgres:
      image: postgres:15-alpine
      container_name: SSHProxy-postgres
      environment:
        POSTGRES_USER: SSHProxy_user
        POSTGRES_PASSWORD: SSHProxy_password
        POSTGRES_DB: SSHProxy_db
      ports:
       - '5432:5432'
      volumes:
       - postgres_data:/var/lib/postgresql/data
      healthcheck:
       test: ["CMD-SHELL", "pg_isready  -U SSHProxy_user"]
       interval: 10s
       timeout: 5s
       retries: 5

volumes:
  postgres_data:

